version: '3'

services:

  app:
    container_name: "java-app"
    build: ./
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: "postgres"
    image: 'postgres'
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "g12nokona"
