version: '3'

services:

  app:
    container_name: "java-app"
    build: ./
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      JWT_REFRESH_SECRET:
      JWT_SIGNATURE_GENERATOR_SECRET:

  postgres:
    container_name: "postgres"
    image: 'postgres'
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_URL:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
