global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'micronaut-micrometer'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
